# Generated by Django 4.2.1 on 2023-05-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_basecustomer_user_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sum_price',
        ),
    ]
