# Generated by Django 4.2.1 on 2023-05-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_timetable_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
    ]
