# Generated by Django 4.2.1 on 2023-06-07 13:24

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_customer_name_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main_page.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(),
        ),
    ]
