# Generated by Django 4.2.1 on 2023-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_services_image_alter_services_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateField(),
        ),
    ]
